### ISSUE TITLE
Cyb landing make up

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb-parity#11]
@asadovka commented on [Wed Sep 05 2018](https://github.com/cybercongress/cyb/issues/230)

@asadovka commented on [Mon Jul 02 2018](https://github.com/cybercongress/congress/issues/90)

https://cybercongress.github.io/cyb/

**Comment by asadovka** [comment]
-desktop
-tablet
-mobile

**Comment by SaveTheAles** [comment]
@xhipster @Pechalka @Olga584 

Now landing available at https://cybercongress.github.io/cyb/
Background with rings and buttons waiting for the small refactoring but desktop tablet and mobile version are ready to review. 

@Olga584 Compare with your design my adaptive realisation pls
@Pechalka review code pls
@xhipster review context pls
