### ISSUE TITLE
Can not link app

### ISSUE THREAD

**Issue by mastercyb** [asadovka/cyb-parity#25]
### Current Behavior
Trying create simple app:
> cyb link

Error: ENOENT: no such file or directory, open './manifest.json'

### Screen
<img width="425" alt="screen shot 2018-09-28 at 16 30 40" src="https://user-images.githubusercontent.com/410789/46211560-80bb1b00-c33c-11e8-82dc-32786053b951.png">

### Expected Behavior
Is described on `/ App development tool` in cyb

### Definition of Done
App is linked to chaingear

**Comment by asadovka** [comment]
@xhipster after "init" command you should go to the generated app folder and then execute "link".

For example:

- cyb init  test_app
- cd test_app
- cyb link

**Comment by mastercyb** [comment]
please, fix manual

**Comment by asadovka** [comment]
solved
