### ISSUE TITLE
Design standard modal dialog for signing stuff

### ISSUE THREAD

**Issue by mastercyb** [asadovka/cyb-parity#34]
### User Story

Current behavior of signer dialog (it is then I put my password to sign tx) is not obvious. Signing is very important part of web3 experience

### Solution

My proposal is a modal dialog for every singing request.

### Definition of Done

Every signing request will (1) block my behavior before decision will be made and (2) blur my focus from everything happens around.

**Comment by asadovka** [comment]
duplicate https://github.com/cybercongress/cyb/issues/5
