### ISSUE TITLE
Mobile & tablet cyb landing design

### ISSUE THREAD

**Issue by asadovka** [asadovka/cyb-parity#42]
@asadovka commented on [Mon Oct 01 2018](https://github.com/cybercongress/old_cyb/issues/233)

adaptize design for tablet & mobile screens

**Comment by asadovka** [comment]
Cyb full
![image](https://user-images.githubusercontent.com/17406355/46538999-123b0780-c8be-11e8-8771-9aac082574e9.png)

Cyb 1200
![image](https://user-images.githubusercontent.com/17406355/46539051-37c81100-c8be-11e8-91ac-ea0c5066f85e.png)

Cyb 768
![image](https://user-images.githubusercontent.com/17406355/46539256-a86f2d80-c8be-11e8-8089-f66d3b33999d.png)

Cyb 992
![image](https://user-images.githubusercontent.com/17406355/46539269-b2912c00-c8be-11e8-86be-f50116d7295f.png)

**Comment by asadovka** [comment]
@Olga584 we need to make fonts bigger. for mobile version they are too small.

**Comment by mastercyb** [comment]
Please, forget about medium, change to Steem

**Comment by mastercyb** [comment]
Please remove non existent things from dapp store such as multiblockchain wallet and token monitor

**Comment by asadovka** [comment]
@xhipster due to new concept we will have no links at the bottom of the page (like in chaingear landing)

**Comment by asadovka** [comment]
final result is here:
https://cyb.ai/
